# Use postgres/example user/password credentials
version: '3.1'

services:
  app:
    build: .
    ports:
      - '3000:3000'

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./pgdata:/var/lib/postgresql
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
